- name: install maven
  ansible.builtin.import_role:
   name: common
   tasks_from: maven

- name: create user-dir-extract
  ansible.builtin.import_role:
   name: common
   tasks_from: user-dir-extract

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args: 
    chdir: /app
  
- name: move the shipping.jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: copy-daemon-start
  ansible.builtin.import_role:
   name: common
   tasks_from: copy-daemon-start

- name: load shipping
  ansible.builtin.import_role:
   name: common
   tasks_from: load-mysql-ship-schema



