- name: check user roboshop exist or not
  ansible.builtin.command: id roboshop
  register: srikar
  ignore_errors: true

- name: create user roboshop
  ansible.builtin.user:
   name: roboshop
  when: srikar.rc != 0 

- name: check directory app exist or not
  ansible.builtin.stat:
   path: /app
  register: srikar

- name: print the directory 
  ansible.builtin.debug:
   msg: "output is: {{srikar}}"

- name: create the directory
  ansible.builtin.file:
   path: /app
   state: directory 
  when: srikar.stat.exists == False

- name: "download {{component}} artifact"
  ansible.builtin.get_url:
   url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
   dest: /tmp

- name: unzip {{component}}
  ansible.builtin.unarchive:
   src: /tmp/{{component}}.zip
   dest: /app
   remote_src: yes